apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zingybank-dev-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LycanTech/ZingyBank.git
    targetRevision: dev
    path: infrastructure/k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: zingybank-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
