image:
  repository: zingybankdev.azurecr.io/zingybank/api-gateway
  tag: "dev-latest"
service:
  port: 8080
replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi
env:
  SPRING_PROFILES_ACTIVE: dev
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_SERVICE_NAME: api-gateway
  VAULT_ADDR: http://vault:8200
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities: {}