image:
  repository: zingybankdev.azurecr.io/zingybank/auth-service
  tag: "dev-latest"
  pullPolicy: Always
service:
  port: 8081
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 768Mi
env:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_URL: "jdbc:postgresql://zingybank-postgres-dev.postgres.database.azure.com:5432/zingybank_auth?sslmode=require"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_SERVICE_NAME: auth-service
secrets:
  DB_USERNAME: db-username
  DB_PASSWORD: db-password
podSecurityContext:
  runAsNonRoot: false
  runAsUser: 0
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  capabilities:
    drop: []
livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: 8081
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: 8081
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
