image:
  repository: ghcr.io/lycantech/zingybank/transaction-service
  tag: "main-9d4bc0c"
service:
  port: 8083
replicaCount: 2
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
env:
  SPRING_PROFILES_ACTIVE: staging
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_SERVICE_NAME: transaction-service
  VAULT_ADDR: http://vault:8200
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
