image:
  repository: ghcr.io/lycantech/zingybank/auth-service
  tag: "main-7b9edac"
service:
  port: 8081
replicaCount: 3
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
env:
  SPRING_PROFILES_ACTIVE: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_SERVICE_NAME: auth-service
  VAULT_ADDR: http://vault:8200
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
