image:
  repository: ghcr.io/lycantech/zingybank/loan-service
  tag: "main-b226ae2"
service:
  port: 8085
replicaCount: 3
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi
env:
  SPRING_PROFILES_ACTIVE: production
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
  OTEL_SERVICE_NAME: loan-service
  VAULT_ADDR: http://vault:8200
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
